replicaCount: 1

image:
  repository: miskinich/api-bootcampclt
  tag: "1.0"
  pullPolicy: Always

app:
  applicationName: api-bootcampclt
  containerPort: 8080
  env:
    aspnetcoreEnvironment: Development

service:
  type: NodePort
  port: 80
  targetPort: 8080

postgres:
  host: postgres-svc
  port: 5432
  database: hardwareCLT
  username: postgres
  password: "a.123456"   # Para demo local. En equipos reales, no commitear.

serilog:
  seq:
    serverUrl: "http://seq.infra.svc.cluster.local:80"
